config/routes.rb
TwitterToKippt::Application.routes.draw do
  
  root :to => 'home#index'
  
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'
  
  match 'destroy', to: 'home#delete_account', as: 'delete_account'
  match 'auth_kipt', to: 'sessions#auth_kippt', as: 'auth_kipt'
  post 'auth_kipt/postback', to: 'sessions#auth_kipt_postback', as: 'auth_kipt_create'
  match 'change-list', to: 'home#change_kippt_list', as: 'change_list'
  post 'update-list', to: 'home#update_kippt_list', as: 'update_list'
  

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :kippt_token, :kippt_username, :last_tweet_id, :twitter_token, :twitter_secret, :twitter_uid, :twitter_username, :twitter_avatar, :time_of_last_sync, :kippt_list_id
  
  scope :authorised, lambda { where("kippt_token IS NOT NULL AND kippt_username IS NOT NULL AND twitter_token IS NOT NULL AND twitter_secret IS NOT NULL") }
  
  def self.from_omniauth(auth)
    user = where(:twitter_uid => auth["uid"]).first
    
    if !user.nil?
      p auth.to_json
      
      user.twitter_token = auth["credentials"]["token"]
      user.twitter_secret = auth["credentials"]["secret"]
      user.save
      
      return user
    end
    
    create_from_omniauth(auth)
  end

  def self.create_from_omniauth(auth)
    create! do |user|
      user.twitter_uid = auth["uid"]
      user.twitter_username = auth["info"]["nickname"]
      user.twitter_avatar = auth["info"]["image"]
      user.twitter_token = auth["credentials"]["token"]
      user.twitter_secret = auth["credentials"]["secret"]
    end
  end
  
  def kippt_authorized?
    (!self.kippt_username.blank? && !self.kippt_token.blank?)
  end  
  
  def update_kippt_details(account)
    self.kippt_username = account.username
    self.kippt_token = account.token
    self.save
  end
  
  def twitter
    Twitter.configure do |config|
      config.consumer_key = ENV["TWITTER_KEY"]
      config.consumer_secret = ENV["TWITTER_SECRET"]
      config.oauth_token = self.twitter_token
      config.oauth_token_secret = self.twitter_secret
    end
    Twitter::Client.new
  end
  
  def kippt
    Kippt::Client.new(username: self.kippt_username, token: self.kippt_token)
  end
  
  def last_tweet
    self.last_tweet_id.nil? ? 100 : self.last_tweet_id
  end
  
  def last_sync
    return self.time_of_last_sync.strftime("%D %R") unless self.time_of_last_sync.nil?
    return "N/A" if self.time_of_last_sync.nil?
  end
  
  def current_kippt_list
    if !self.kippt_list_id.nil?
      list = self.kippt.lists[self.kippt_list_id]
      return list.title unless list.nil? 
    end
    return "Inbox"  
  end
  
  def delete_account
    self.kippt_username = nil
    self.kippt_token = nil
    self.twitter_token = nil
    self.twitter_secret = nil
    self.save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  private

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    helper_method :current_user
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  before_filter :signed_in_user?, :only => [:delete_account, :change_kippt_list, :update_kippt_list]
  before_filter :kippt_auth?, :only => [:change_kippt_list, :update_kippt_list]
  
  def index
    
  end
  
  def delete_account
    current_user.delete_account
    session[:user_id] = nil
    redirect_to root_path, notice: "Your account has been deleted."
  end
  
  def change_kippt_list
    @lists = current_user.kippt.lists.all
  end
  
  def update_kippt_list
    if params[:user][:kippt_list_id]
      current_user.kippt_list_id = params[:user][:kippt_list_id]
      current_user.save
      redirect_to root_path, notice: "Kippt list updated"
    end
  end
  
  private 
  
  def signed_in_user?
    if current_user.nil?
      redirect_to root_path, notice: "Unauthorised"
      return
    end
  end
  
  def kippt_auth?
    if !current_user.kippt_authorized? 
      redirect_to root_path, notice: "Unauthorised"
      return
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url, notice: "Signed in!"
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Signed out!"
  end
    
  def auth_kippt
    
  end
  
  def auth_kipt_postback
    if params[:kippt_username] && params[:kippt_password]
      # Try and auth with Kippt
      kippt = Kippt::Client.new(username: params[:kippt_username], password: params[:kippt_password]) 
      account = kippt.account rescue nil
      
      unless account.nil?
        current_user.update_kippt_details(account)
        redirect_to root_url, notice: "Kippt account authorised!"
        return
      end
    end
    
    flash[:notice] = 'Invalid credentials'
    render :action => "auth_kippt" 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/_signed_in.html.erb
<h1>Hi, <%= current_user.twitter_username %></h1>

<% if !current_user.kippt_authorized? %>
  <p>It looks like you haven't authorised us for use with your Kippt account yet.</p> 
  <p><%= link_to "Authorise Kippt", auth_kipt_path %></p>
  
<% else %>
  <p>
    The last time we synched your favourites to Kippt was: <strong><%= current_user.last_sync %></strong>. Syncing your favourites to the list <strong><%= current_user.current_kippt_list %></strong>
  </p>

  <p>
    <%= link_to "Change the list where my Kippt's get saved", change_list_path %>
  </p>
  
<% end %>

<p>
  <%= link_to "Stop this and delete my account please", delete_account_path %><br />
  <%= link_to "Sign out", "/signout" %>
</p>

app/views/home/_signed_out.html.erb
<h1>Automatically import your Twitter Favourites to Kippt</h1>
<p>You'll need to connect with Twitter and authenticate with Kippt in order to activate the service. You'll only need to do this once, we'll take care of the rest.</p>
<p>
  <%= link_to "Sign in with Twitter", "/auth/twitter" %>
</p>

app/views/home/change_kippt_list.html.erb
<h1>Change where your Kippt's get saved</h1>
<p>
  If you wish to change the list your new Kippt's go to, please select it here. (Defaults to Inbox)
</p>

<%= form_tag update_list_path do %>
  <%= select("user", "kippt_list_id", @lists.collect { |l| [l.title, l.id] }, :prompt => 'Select List', :selected => current_user.kippt_list_id ) %>
  <%= submit_tag("Update") %>
<% end %>

<p>
  <%= link_to "Go back", root_path %>
</p>

app/views/home/index.html.erb
<%= render 'signed_out' if current_user.nil? %>
<%= render 'signed_in' if current_user %>

  
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter Favourites to Kippt Inbox - Automagically!</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="wrapper">
    
    <% if flash[:warning] or flash[:notice] %>
      <div id="notice" <% if flash[:warning] %>class="warning"<% end %>>
        <%= flash[:warning] || flash[:notice] %>
      </div>
    <% end %>
    
    <%= yield %>
    <footer>
      <p>A little thing made by <%= link_to "cjbell", "http://cjbell.co" %></p>
    </footer>
  </div>
  <script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-33797976-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

  </script>
</body>
</html>